---
# Configuración oficial de despliegue automático cPanel Git™ Version Control
# Servidor: cpanel.cofiza.com | Usuario: cofizaco | Dominio: cofiza.com
deployment:
  tasks:
    - export DEPLOYPATH=/home/cofizaco/public_html/
    # Copia el build listo para producción a public_html
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
